import assert from 'node:assert/strict';
import fs from 'node:fs';
import { chromium } from 'playwright';

const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 900, height: 650 } });
const errors = [];
page.on('pageerror', error => errors.push(String(error)));
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
const canvas = page.locator('#game');
const state = async () => JSON.parse(await page.evaluate(() => window.render_game_to_text()));
fs.mkdirSync('output/layout-visual', { recursive: true });
await page.goto('http://127.0.0.1:5173/?seed=7', { waitUntil: 'networkidle' });
await page.keyboard.press('Enter');
assert.equal((await state()).mode, 'route');
await page.screenshot({ path: 'output/layout-visual/route-small.png' });
await page.keyboard.press('1');
assert.equal((await state()).mode, 'combat');
await page.screenshot({ path: 'output/layout-visual/combat-small.png' });
await page.keyboard.press('i');
assert.equal((await state()).battleNotesOpen, true);
await page.screenshot({ path: 'output/layout-visual/details-small.png' });
await page.keyboard.press('c');
assert.equal((await state()).loadoutOpen, true);
await page.screenshot({ path: 'output/layout-visual/loadout-small.png' });
const bounds = await canvas.boundingBox();
assert.ok(bounds.x >= 0 && bounds.y >= 0 && bounds.x + bounds.width <= 900 && bounds.y + bounds.height <= 650);
assert.deepEqual(errors, []);
await browser.close();
