import assert from 'node:assert/strict';
import fs from 'node:fs';
import { chromium } from 'playwright';
import { newGame, startGame, chooseRoute, resolveMission, endTurn, projectEndTurn, playCard, chooseReward, choosePractice, selectRole } from '../src/battle-game.js';

const stable = newGame(42);
startGame(stable);
assert.deepEqual(stable.routeForecast.map(stop => stop.encounter), [2, 3]);
assert.equal(stable.routeChoices[0].mission, 'handoff');
chooseRoute(stable, 0);
assert.equal(stable.mission.id, 'handoff');
const before = JSON.stringify(stable);
const preview = projectEndTurn(stable);
assert.equal(JSON.stringify(stable), before, 'preview must not advance or alter the real run');
assert.equal(preview.hp, stable.hp - preview.damage);
stable.sp = 3;
assert.equal(resolveMission(stable), true);
assert.equal(stable.mission.resolved, true);
endTurn(stable);
assert.equal(stable.mission.failed, false);

const audit = newGame(43);
startGame(audit);
chooseRoute(audit, 1);
assert.equal(audit.mission.id, 'audit');
audit.sp = 0;
assert.equal(projectEndTurn(audit).debtAdded, 1);
endTurn(audit);
assert.equal(audit.projectDebt, 1);

const linked = newGame(12);
startGame(linked);
chooseRoute(linked, 0);
linked.enemies[0].hp = 1;
linked.hand = ['patch']; linked.sp = 3;
playCard(linked, 0);
assert.equal(linked.mode, 'reward');
chooseReward(linked, 0);
assert.equal(linked.mode, 'practice');
choosePractice(linked, 'cohesion');
assert.equal(linked.mode, 'route');
assert.equal(linked.routeChoices[0].mission, 'coupled');
chooseRoute(linked, 0);
const linkedPower = linked.enemies[1].power;
linked.hand = ['charter', 'patch']; linked.sp = 3;
playCard(linked, 0);
assert.equal(linked.sp, 3, 'first role-family skill refunds its SP');
linked.enemies[0].hp = 1;
playCard(linked, 0);
assert.equal(linked.enemies.length, 1);
assert.equal(linked.enemies[0].power, linkedPower - 1);

const automated = newGame(13);
automated.practice = 'automation';
startGame(automated); chooseRoute(automated, 0);
assert.equal([...automated.hand, ...automated.drawPile].filter(id => id === 'defect').length, 1);
automated.hand = ['pipeline']; automated.sp = 3;
playCard(automated, 0);
assert.equal(automated.initiatives[0].remaining, 1);
endTurn(automated);
assert.ok(automated.activeInitiatives.includes('pipeline'));

const triaged = newGame(14);
triaged.practice = 'triage';
startGame(triaged); chooseRoute(triaged, 0);
triaged.enemies[0].weak = 1;
triaged.hand = ['patch']; triaged.sp = 3;
const hpBefore = triaged.enemies[0].hp;
playCard(triaged, 0);
assert.ok(hpBefore - triaged.enemies[0].hp >= 13);

for (const [role, added] of [['architect', 'reserve'], ['debugger', 'probe'], ['producer', 'quiet']]) {
  const kit = newGame(55);
  selectRole(kit, role);
  kit.masteryKit = true;
  startGame(kit);
  assert.ok(kit.deck.includes(added), `${role} kit should replace one starter skill`);
}

const lethal = newGame(33);
startGame(lethal); chooseRoute(lethal, 0);
lethal.hp = 1; lethal.block = 0;
assert.equal(projectEndTurn(lethal).lethal, true);
endTurn(lethal);
assert.equal(lethal.mode, 'end');
assert.ok(lethal.deathCause.includes(lethal.enemies[0].name));

const browser = await chromium.launch({ headless: true });
fs.mkdirSync('output/maturity-upgrade', { recursive: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
const errors = [];
page.on('pageerror', error => errors.push(String(error)));
const state = async () => JSON.parse(await page.evaluate(() => window.render_game_to_text()));
await page.goto('http://127.0.0.1:5173/?seed=42');
await page.waitForFunction(() => typeof window.render_game_to_text === 'function');
await page.evaluate(() => localStorage.clear());
await page.reload();
await page.keyboard.press('Enter');
const route = await state();
assert.equal(route.mode, 'route');
assert.equal(route.routeForecast.length, 2);
await page.reload();
assert.equal((await state()).mode, 'intro');
assert.equal((await state()).savedRunAvailable, true);
await page.locator('#game').screenshot({ path: 'output/maturity-upgrade/continue.png' });
await page.keyboard.press('l');
assert.equal((await state()).mode, 'route');
assert.deepEqual((await state()).routeChoices, route.routeChoices);
await page.keyboard.press('1');
const combat = await state();
assert.equal(combat.mode, 'combat');
assert.equal(combat.mission.id, 'handoff');
assert.ok(combat.endTurnPreview);
await page.locator('#game').screenshot({ path: 'output/maturity-upgrade/mission-preview.png' });
await page.keyboard.press('m');
await page.keyboard.press('Enter');
assert.equal((await state()).mode, 'intro');
await page.keyboard.press('l');
assert.equal((await state()).mode, 'combat');
assert.equal((await state()).turn, combat.turn);
for (let turn = 0; turn < 50 && (await state()).mode === 'combat'; turn++) await page.keyboard.press('Space');
assert.equal((await state()).mode, 'end');
assert.ok((await state()).deathCause);
assert.equal((await state()).savedRunAvailable, false);
const recorded = await page.evaluate(() => JSON.parse(localStorage.getItem('deadline-disaster-career-v1')));
assert.ok(recorded.metrics.routeKinds.combat >= 1);
assert.ok(Object.keys(recorded.metrics.defeats).length >= 1);
await page.evaluate(() => localStorage.setItem('deadline-disaster-career-v1', JSON.stringify({ runs: 1, wins: 1, best: 500, bosses: [], roles: ['architect'], charters: [], bestByRole: {}, bestByCharter: {}, mastery: { architect: { runs: 1, wins: 1, bosses: 1, briefs: 6, missions: 5 } }, runHistory: [] })));
await page.reload();
await page.keyboard.press('y');
assert.equal((await state()).masteryKit, true);
await page.keyboard.press('j');
const canvas = page.locator('#game'), box = await canvas.boundingBox();
await page.mouse.click(box.x + 600 * box.width / 1200, box.y + 235 * box.height / 800);
assert.equal((await state()).archivePage, 'mastery');
await canvas.screenshot({ path: 'output/maturity-upgrade/mastery.png' });
await page.mouse.click(box.x + 820 * box.width / 1200, box.y + 235 * box.height / 800);
assert.equal((await state()).archivePage, 'insights');
await canvas.screenshot({ path: 'output/maturity-upgrade/insights.png' });
assert.equal(errors.length, 0, errors.join('\n'));
await browser.close();
console.log('Maturity upgrade passed: route forecast, practice engines, missions, exact preview, save/resume, death recap, and mastery kit.');
