import assert from 'node:assert/strict';
import { newGame, selectRole, startGame, chooseRoute, canChooseEvent, chooseEvent, canBuyShop, buyShop, leaveShop, playCard, useTrinket, endTurn, intentFor, chooseReward } from '../src/battle-game.js';

const producer = newGame(7);
assert.equal(selectRole(producer, 'producer'), true);
assert.equal(producer.hp, 78);
assert.equal(producer.credits, 18);
assert.ok(producer.deck.includes('scopelock'));
assert.deepEqual(producer.trinkets, ['stopwatch']);
assert.equal(selectRole(producer, 'debugger'), true);
assert.equal(producer.hp, 72);
assert.equal(producer.inventory.filter(id => id === 'duck').length, 2);
assert.ok(producer.deck.includes('rootcause'));
assert.deepEqual(producer.trinkets, ['paperclip']);

const story = newGame(7), storyReplay = newGame(7);
startGame(story); startGame(storyReplay);
assert.deepEqual(story.routeChoices, storyReplay.routeChoices);
assert.equal(story.routeChoices.length, 3);
chooseRoute(story, 2); chooseRoute(storyReplay, 2);
assert.equal(story.mode, 'event');
assert.equal(story.eventId, storyReplay.eventId);
const choice = [0, 1, 2].find(i => canChooseEvent(story, i));
assert.ok(choice !== undefined);
chooseEvent(story, choice);
assert.equal(story.mode, 'combat');
assert.equal(story.enemies.length, 1);
assert.ok(story.enemies[0].maxHp >= 30, 'detours should carry a combat cost');
assert.equal(story.floor, 0, 'event should precede its fight');

const flow = newGame(22);
startGame(flow); chooseRoute(flow, 0);
flow.hand = ['review', 'patch']; flow.sp = 3; flow.enemies[0].hp = 30; flow.enemies[0].maxHp = 30;
assert.equal(playCard(flow, 0), true);
assert.equal(flow.flow, 1);
assert.equal(playCard(flow, 0), true);
assert.equal(flow.enemies[0].hp, 21, 'Flow should add 2 damage to an attack');
flow.hand = ['review', 'automation']; flow.sp = 3; flow.flow = 0;
playCard(flow, 0); playCard(flow, 0);
assert.equal(flow.flow, 2);
assert.equal(flow.sp, 2, 'Automation should refund SP at 2 Flow');
flow.hand = ['handoffmap', 'patch', 'patch', 'review', 'review']; flow.sp = 3;
playCard(flow, 0);
assert.ok(flow.hand.length <= 5, 'draw effects must not overflow the visible hand');
assert.equal(useTrinket(flow, 0), true);
assert.equal(useTrinket(flow, 0), false, 'a trinket works once per fight');
assert.equal(flow.usedTrinkets.length, 1);

const relic = newGame(31); relic.relics.push('binder', 'thread');
startGame(relic); chooseRoute(relic, 0);
relic.hand = ['review', 'review']; relic.sp = 3;
playCard(relic, 0);
assert.equal(relic.block, 10, 'binder boosts the first skill only');
playCard(relic, 0);
assert.equal(relic.block, 17);
useTrinket(relic, 0);
assert.equal(relic.flow, 3, 'Red Thread grants Flow on trinket use');
const clean = newGame(32); clean.relics.push('interface'); startGame(clean); chooseRoute(clean, 0);
clean.hand = ['review']; clean.sp = 3; playCard(clean, 0);
assert.equal(clean.block, 9);
useTrinket(clean, 0);
assert.equal(clean.block, 16, 'Clean Interface boosts block cards, not trinkets');

const tax = newGame(34); startGame(tax); chooseRoute(tax, 0);
tax.enemies = [{ id: 'chimera', name: 'Approval Chimera', hp: 34, maxHp: 34, block: 0, weak: 0, vulnerable: 0, step: 0, power: 0 }];
assert.equal(intentFor(tax.enemies[0]).label, 'TAX 1 SP');
endTurn(tax);
assert.equal(tax.sp, 2, 'tax removes next-turn SP');
const split = newGame(35); startGame(split); chooseRoute(split, 0);
split.enemies = [{ id: 'slime', name: 'Regression Slime', hp: 27, maxHp: 27, block: 0, weak: 0, vulnerable: 0, step: 1, power: 0 }];
endTurn(split);
assert.equal(split.enemies.length, 2, 'slime splits into an additional target');
assert.equal(split.enemies[1].hp, 14);

const market = newGame(6);
startGame(market); chooseRoute(market, 0);
market.enemies[0].hp = 1; market.hand = ['patch']; market.sp = 3;
playCard(market, 0);
assert.equal(market.mode, 'reward');
assert.equal(market.credits, 30);
assert.equal(market.lastPerfect, true);
chooseReward(market, 2);
assert.equal(market.mode, 'route');
assert.equal(market.routeChoices[2].kind, 'shop');
chooseRoute(market, 2);
assert.equal(market.mode, 'shop');
assert.equal(canBuyShop(market, 0), true);
market.credits = 55;
const card = market.shopStock[0].id, credits = market.credits, deckSize = market.deck.length;
assert.equal(buyShop(market, 0), true);
assert.equal(market.credits, credits - market.shopStock[0].price);
assert.equal(market.deck.length, deckSize + 1);
assert.equal(market.deck.at(-1), card);
assert.equal(buyShop(market, 0), false, 'sold stock cannot be purchased twice');
assert.equal(canBuyShop(market, 3), true);
assert.equal(buyShop(market, 3), true);
assert.equal(market.trinkets.length, 2);
assert.equal(leaveShop(market), true);
assert.equal(market.mode, 'combat');
assert.equal(market.floor, 1, 'shopping should precede its fight');

const elite = newGame(77); startGame(elite); chooseRoute(elite, 1);
elite.enemies[0].hp = 1; elite.hand = ['patch']; elite.sp = 3;
playCard(elite, 0);
assert.equal(elite.mode, 'reward');
assert.equal(elite.trinkets.length, 2, 'elite cache should fill the second trinket slot');

console.log('Mature systems passed: roles, detours, Flow, trinkets, relic synergies, new enemy intents, perfect payout, shop purchases, and combat continuation.');
