import fs from 'node:fs';
import assert from 'node:assert/strict';
import { chromium } from 'playwright';

const out = 'output/strategy-visual'; fs.mkdirSync(out, { recursive: true });
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
const canvas = page.locator('#game');
const errors = [];
page.on('pageerror', error => errors.push(String(error)));
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
const state = async () => JSON.parse(await page.evaluate(() => window.render_game_to_text()));
const fresh = async seed => { await page.goto(`http://127.0.0.1:5173/?seed=${seed}`, { waitUntil: 'networkidle' }); };

await fresh(123);
await page.keyboard.press('m');
assert.equal((await state()).mode, 'challenge');
await canvas.screenshot({ path: `${out}/challenge.png` });
await page.keyboard.press('2');
assert.equal((await state()).challenge, 'crunch');
await page.keyboard.press('Enter');
assert.equal((await state()).mode, 'route');
assert.equal((await state()).projectDebt, 4);
await canvas.screenshot({ path: `${out}/route-options.png` });
await page.keyboard.press('p');
assert.equal((await state()).mode, 'charter');
await canvas.screenshot({ path: `${out}/charter.png` });
await page.keyboard.press('2');
assert.equal((await state()).charter, 'surgical');
assert.equal((await state()).specialist.id, 'qa');
await page.keyboard.press('k');
assert.equal((await state()).mode, 'contract');
await canvas.screenshot({ path: `${out}/contract.png` });
await page.keyboard.press('1');
assert.equal((await state()).contract.id, 'clean');
await page.keyboard.press('1');
assert.equal((await state()).mode, 'combat');
assert.equal((await state()).hand.length, 4);
await canvas.screenshot({ path: `${out}/surgical-combat.png` });
await page.keyboard.press('s');
assert.equal((await state()).enemies[0].mark, 3);

await fresh(456);
await page.keyboard.press('m'); await page.keyboard.press('4');
assert.equal((await state()).challenge, 'daily');
assert.equal((await state()).seed, Number((await state()).dailyDate.replaceAll('-', '')));
await page.keyboard.press('Enter');
assert.equal((await state()).mode, 'route');
assert.equal(errors.length, 0, errors.join('; '));
console.log('Strategy visual passed: challenge, daily seed, charter, contract, surgical combat, and no browser errors.');
await browser.close();
