import assert from 'node:assert/strict';
import { newGame, startGame, chooseRoute, choosePractice, openHiring, hireSpecialist, specialistPrice, useSpecialist, useRoleAbility, useTrinket, playCard, intentFor, chooseReward, chooseTune, chooseUpgrade, debtTier, cardInfo } from '../src/battle-game.js';

const team = newGame(42); startGame(team);
assert.equal(openHiring(team), true);
assert.equal(specialistPrice(team), 12);
assert.equal(hireSpecialist(team, 'qa'), true);
assert.equal(team.credits, 2);
assert.equal(team.specialist, 'qa');
chooseRoute(team, 0);
assert.equal(team.mode, 'combat');
assert.equal(useSpecialist(team, 0), true);
assert.equal(team.enemies[0].mark, 2);
assert.equal(team.enemies[0].weak, 1);
assert.equal(useSpecialist(team, 0), false);
assert.equal(useRoleAbility(team), false, 'architect must have Block before banking');
team.objective = { id: 'team', progress: 0, done: false };
useTrinket(team, 0);
assert.equal(useRoleAbility(team), true);
assert.equal(team.objective.done, true);

const boss = newGame(11); startGame(boss); boss.floor = 2; boss.routeChoices = [{ ids: ['goblin'], boss: true, label: 'Boss' }];
chooseRoute(boss, 0);
assert.equal(boss.enemies[0].phase, 1);
boss.enemies[0].hp = 40; boss.hand = ['patch']; boss.sp = 3;
playCard(boss, 0);
assert.equal(boss.enemies[0].phase, 2);
assert.equal(boss.enemies[0].step, 0);
assert.match(intentFor(boss.enemies[0]).label, /DRAIN/);
boss.enemies[0].hp = 19; boss.hand = ['patch']; boss.sp = 3;
playCard(boss, 0);
assert.equal(boss.enemies[0].phase, 3);
assert.match(intentFor(boss.enemies[0]).label, /TAX/);

const debt = newGame(17); startGame(debt); chooseRoute(debt, 0);
debt.hand = ['panic']; debt.sp = 3; playCard(debt, 0);
assert.equal(debt.projectDebt, 1);
debt.projectDebt = 9;
assert.equal(debtTier(debt), 2);
debt.enemies[0].hp = 1; debt.hand = ['patch']; debt.sp = 3;
debt.objective = { id: 'quick', progress: 0, done: false };
playCard(debt, 0);
assert.equal(debt.lastObjective, true);
assert.equal(debt.projectDebt, 8);
assert.ok(debt.lastPayout >= 19);
assert.equal(chooseReward(debt, 3), true);
const audit = debt.tuneChoices.findIndex(c => c.type === 'audit');
assert.ok(audit >= 0);
chooseTune(debt, audit);
assert.equal(debt.projectDebt, 4);
if (debt.mode === 'practice') choosePractice(debt, 'cohesion');
assert.equal(debt.mode, 'route');

const upgrade = newGame(19); startGame(upgrade); chooseRoute(upgrade, 0);
upgrade.enemies[0].hp = 1; upgrade.hand = ['patch']; upgrade.sp = 3; playCard(upgrade, 0);
chooseReward(upgrade, 3);
const choice = upgrade.tuneChoices.findIndex(c => c.type === 'upgrade');
assert.ok(choice >= 0);
const id = upgrade.tuneChoices[choice].id;
chooseTune(upgrade, choice);
assert.equal(upgrade.mode, 'upgrade');
chooseUpgrade(upgrade, 'flex');
assert.ok(upgrade.deck.includes(`${id}*`));
assert.equal(cardInfo(`${id}*`).branch, 'flex');
if (upgrade.mode === 'practice') choosePractice(upgrade, 'cohesion');
assert.equal(upgrade.mode, 'route');
const flexAttack = newGame(27); startGame(flexAttack); chooseRoute(flexAttack, 0);
flexAttack.hand = ['patch*']; flexAttack.sp = 3;
playCard(flexAttack, 0);
assert.equal(flexAttack.block, 3, 'Flex attack grants Block');
flexAttack.hand = ['review*']; flexAttack.drawPile = ['patch']; flexAttack.sp = 3;
playCard(flexAttack, 0);
assert.equal(flexAttack.block, 10);
assert.equal(flexAttack.hand[0], 'patch', 'Flex skill draws a card');

const late = newGame(25); startGame(late); late.floor = 6; late.credits = 30;
openHiring(late); hireSpecialist(late, 'captain');
assert.equal(late.onboardingPending, 2);
late.routeChoices = [{ ids: ['scope'], label: 'Late incident' }];
chooseRoute(late, 0);
assert.equal(late.sp, 1);
assert.equal(late.onboardingPending, 0);
late.burnout = 1;
assert.equal(useSpecialist(late), true);
assert.equal(late.sp, 2);
assert.equal(late.burnout, 0);

console.log('Systems depth passed: hiring, onboarding, support action, boss phases, Debt, objective bonus, audit, and Flex upgrade.');
